Sect Buffs and Mapping Consistency
fulpstation/fulpstation pull request #1004
Opened 2023-06-07 07:19 UTC by carlopault

## Why It's Good For The Game

Mapping consistency is a good thing. Punished Sect sucks, Mechanical God favor cost has been too high, and the Greed God's drawback of paying for bible heals is too high to be worth it when bible heals would otherwise be free. Just making these sects more favorable so that the chaplain doesn't spend 50+ minutes for a handicap (Punished Sect) or boon they can't really make use of since it is too late into the round (Mechanical God).

## Changelog

:cl:
add: Added chaplain's cloud chasing book and old shard to every mainline map for consistency
balance: Mechanical God favor costs reduced to be more reasonable
balance: Greedy God bible heal money cost reduced by 20% (50 credits -> 40 credits)
balance: Punished Sect now needs a solid 6 burdens instead of 9
/:cl:

2023-06-07 07:25 UTC, JohnFulpWillard commented
This PR is filled with powercreep and ruins the uniqueness of the smoke books’ intentional limitation from being on all maps

2023-06-07 17:29 UTC, carlopault commented
> This PR is filled with powercreep and ruins the uniqueness of the smoke books’ intentional limitation from being on all maps

Trying to make chaplain sect experience less grindy. The sects I buffed suck to begin with.

2023-06-07 17:31 UTC, JohnFulpWillard commented
Chaplain sects are meant to be grindy because it's not the main point of your role, it's something you do in your spare time to keep you busy.

2023-06-08 00:45 UTC, SgtHunk requested changes
PR this upstream, as this is a change affecting TG features.

2023-06-08 21:46 UTC, carlopault commented
> PR this upstream, as this is a change affecting TG features.

You want me to PR this to the TG github?

2023-06-10 00:37 UTC, SgtHunk commented
> You want me to PR this to the TG github?

Yes, that's our upstream. Fulp repository focuses on fulp-only features for the most part, and we re-direct all changes to TG code upstream unless there is a good reason not to, such as fixing an issue present in Fulp (usually with admins taking notice of this issue and suggesting for the PR to be made).

2023-06-11 03:56 UTC, carlopault commented
> > You want me to PR this to the TG github?
> 
> Yes, that's our upstream. Fulp repository focuses on fulp-only features for the most part, and we re-direct all changes to TG code upstream unless there is a good reason not to, such as fixing an issue present in Fulp (usually with admins taking notice of this issue and suggesting for the PR to be made).

you know the TG codemonkeys wont accept anything that makes anything fun

2023-06-11 03:58 UTC, SgtHunk commented
ok lol

2023-06-11 03:58 UTC, closed without merging

2023-06-11 03:59 UTC, JohnFulpWillard commented
![image](https://github.com/fulpstation/fulpstation/assets/53777086/fc4ef589-3a9d-4630-91df-a8d2d555a7ba)
![image](https://github.com/fulpstation/fulpstation/assets/53777086/6588a7fc-82bd-4883-8d5f-8df64258d8e2)