Removes mayhem in a bottle as a bubblegum drop
fulpstation/fulpstation pull request #1042
Opened 2023-08-29 02:16 UTC by nonameboss2

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-09-05 15:30 UTC, remove32 requested changes

2023-09-05 15:30 UTC, remove32 commented on code/modules/mining/lavaland/necropolis_chests.dm
>  	var/loot = rand(1,2)
this random number isn't used anymore, remove it please

2023-09-05 23:47 UTC, SgtHunk commented
This doesn't feel like it's worth a TG edit, tbh.
This is a TG PR that you brought to Fulp after it got closed, which doesn't address the original cause why that PR was closed.

1- Removing items without adding anything just makes for a less diverse item pool 
2- We adhere to certain guidelines regarding making code contained and modular (keeping it in the fulp folder) due to our constant updates which edit all TG files. If it can't be made modular, then it ought to be something really important to justify it (e.g TGUI).

2023-09-06 01:10 UTC, remove32 commented
good points but I would argue that the item being practically impossible to use without breaking the rules justifies some level of code change to it

2023-09-06 01:44 UTC, SgtHunk commented
> good points but I would argue that the item being practically impossible to use without breaking the rules justifies some level of code change to it

We don't commonly do code changes that restrict the sandbox aspect of the game.
As such, we don't restrict uplink items that you won't be able to use most of the time, such as syndicate bombs.
This isn't an issue with the rules as much as it is an issue with lavaland loot being combat-focused and not utility-focused, which is something to be taken to TG.
The other item in the bubblegum pool, the soulscythe, is JUST a weapon that serves zero purpose in mining.
The maintainer who closed the pull request (Fikou) simply blocked the removal of the mayhem bottle, not the replacement of it. If the author could come up with a good modification to the current loot pool so items are more thematically fitting and serve more utility purposes, mayhem can go.
![4f2517d52469619ade136a0383469bd6](https://github.com/fulpstation/fulpstation/assets/68669754/dc53c858-300f-402c-9dbf-d53c48e284d4)

2023-09-07 16:50 UTC, nonameboss2 commented
"We don't commonly do code changes that restrict the sandbox aspect of the game."

What about bubblegums third drop that was removed, I believe it was called bloody contract. It was seeming a more usable mayhem that was removed without any replacement. You also mentioned something about this not addressing any of the problems it had on tg, which is false since that problems was with the fact that their rules allow that item to be used in escalation.

2023-09-07 16:53 UTC, SgtHunk commented
> What about bubblegums third drop that was removed, I believe it was called bloody contract. It was seeming a more usable mayhem that was removed without any replacement. 

That was a TG Removal, not Fulp's.
https://github.com/tgstation/tgstation/pull/53059

> You also mentioned something about this not addressing any of the problems it had on tg, which is false since that problems was with the fact that their rules allow that item to be used in escalation.

You were already told by a TG maintainer what you could do to get it removed (add a suitable replacement that isn't just murderbonefest tool), the escalation rules are irrelevant.

2023-09-10 20:36 UTC, remove32 commented
I'm in agreement that it'd be preferable to have a replacement compared to a removal. A change to how the bottle of mayhem works OR a custom item to replace it would be acceptable. Given that this changes the nature of the PR, I'll move this to Draft. It's up to you whether you want to pursue changing this any further

2023-09-25 01:04 UTC, closed without merging