Removes the beefmen trauma preferences, lightly reworks the way Sleepless Dreamer works
fulpstation/fulpstation pull request #1043
Opened 2023-09-01 17:34 UTC by FernandoJ8

## About The Pull Request

Since the topic of what to do with beefmen's choice of trauma has been a topic of discussion for some time, here's my latest idea for it:

- Beefmen no longer have a choice of trauma in their preferences. They will spawn with the Sleepless Dreamer trauma and **nothing else.**
- Using phobetor tears will have a chance to cause minor negative effects based on the user's sanity. The lower it is, the worse and more likely the effects will be, and they are now the primary source of hallucinations for beefmen, as well as giving mood debuffs. Examples below: 
<details>

<summary> Neutral to Good </summary>

https://github.com/fulpstation/fulpstation/assets/80640114/c7e99741-45e0-4a59-950e-42df6bd5bdbe

</details>

<details>

<summary> Neutral to Good </summary>

https://github.com/fulpstation/fulpstation/assets/80640114/9efe43f5-a2de-4276-baa6-4bdd3a291a10
</details>

<details>

<summary> Unstable to Good </summary>

https://github.com/fulpstation/fulpstation/assets/80640114/44fd5aee-9968-491b-aeb6-38af2b4b7f40

</details>

<details>

https://github.com/fulpstation/fulpstation/assets/80640114/20bb949d-0c79-4041-a5df-31d68581cb68

<summary> Crazy to Unstable </summary>

</details>

<details>

<summary> Insane to Crazy </summary>

https://github.com/fulpstation/fulpstation/assets/80640114/f32f5d78-d693-4621-8fe0-793a27a892d3

</details>

If you use one while within the Insanity to Crazy range you will also burn out your trauma, and be locked from using tears for 5 minutes.

## Why It's Good For The Game

The current selection of traumas is a bit questionable, since they range from annoying to very easily exploited to soft antag status (I'm looking at you, hypnotism).
I liked the idea of tying a beefman's insanity more closely to their use of the phobetor tears. If travelling through them is a power gained "after undergoing untold psychological hardship", it ought to feel like it. It's a good opportunity for flavour and to encourage managing your mood well, since sanity above great will prevent any downsides.

## Changelog

:cl:
del: Removed beefmen's brain trauma preference.
bal: Lightly reworks phobetor tears. They are now a source of hallucinations and mood debuffs that worsen the lower your sanity is while using them. Using one while crazy will also lock you out of using them for 5 minutes.
/:cl:

2023-09-04 03:24 UTC, remove32 commented
I dig this, but balance is questionable, lets do a TM to get some feedback on it?

2023-09-04 06:13 UTC, FernandoJ8 commented
> I dig this, but balance is questionable, lets do a TM to get some feedback on it?

Sure!

2023-09-06 15:51 UTC, Pepsilawn requested changes

2023-09-06 15:51 UTC, Pepsilawn commented on fulp_modules/features/species/beefmen/phobetor_trauma.dm
> +	to_chat(owner, span_warning("Your feel yourself slipping back into the sleepless dream."))
```suggestion
	to_chat(owner, span_warning("You feel yourself slipping back into the sleepless dream."))
```

2023-09-06 15:51 UTC, Pepsilawn commented on fulp_modules/features/species/beefmen/phobetor_trauma.dm
> +	to_chat(owner, span_notice("Your eyes open once more, and with them unseen pathways."))
```suggestion
	to_chat(owner, span_hypnophrase("Your eyes open once more, and with them unseen pathways."))
```

2023-09-06 15:57 UTC, FernandoJ8 commented on fulp_modules/features/species/beefmen/phobetor_trauma.dm
> +	timeout = 3 MINUTES
it's equivalent to being hungry

2023-09-22 18:08 UTC, merged