Malkavian Dracula Flow
fulpstation/fulpstation pull request #1083
Opened 2023-12-11 18:35 UTC by SilvinaFulp

## About The Pull Request
Adds quotes from Dracula flow to malkav revelations.

## Why It's Good For The Game
It'd be funny to see a bloodsucker be outted because of the zaza.

## Changelog
Adds more quotes to Clan Malkavian.

:cl:
add: Added more things
/:cl:

2023-12-11 18:46 UTC, SilvinaFulp commented
Ignore the 'Add files via upload'

2023-12-11 21:27 UTC, Momo8289 approved these changes

2023-12-11 22:36 UTC, SgtHunk commented
why did u add a whole new file that is an exact copy of the revelations file

2023-12-11 22:38 UTC, Momo8289 requested changes

2023-12-11 22:38 UTC, Momo8289 commented on malkavian_revelations.json
what sgnthunk said, why's this duplicate here?

2023-12-12 05:10 UTC, SilvinaFulp commented
Man where's the delete button

2023-12-12 12:02 UTC, closed without merging

2023-12-12 12:03 UTC, JohnFulpWillard commented
```
Adds more quotes to Clan Malkavian.
🆑
add: Added more things
/:cl:
```

should be

```
🆑
add: Added more quotes to Clan Malkavian.
/:cl:
```