Selene Engineering tweaks and atmos remaster
fulpstation/fulpstation pull request #1179
Opened 2024-03-22 21:15 UTC by Sadboysuss

## About The Pull Request
Changed engineering a bit and fixed some issues. Makes engineering less cramped
I will include all changes in the changelog.
Screenshots:
![image](https://github.com/fulpstation/fulpstation/assets/96586172/b9169262-cc49-412e-b054-c0f50b0d025f)
![image](https://github.com/fulpstation/fulpstation/assets/96586172/497d0a53-9ac0-42e8-bfc7-32857cf8280d)
![image](https://github.com/fulpstation/fulpstation/assets/96586172/9a64b79d-f60a-4ef6-80dc-60bdabd3c611)
![image](https://github.com/fulpstation/fulpstation/assets/96586172/ce70b355-5ea2-41d2-9a45-e75daf8b75a9)

## Why It's Good For The Game
Some features were missing from Selene like external air ports, cyborg charger, proper distro room. I've fixed that

## Changelog

:cl:
add: External air ports, atmos air refilling station, empty cans for atmos, cell charger in engineering, cyborg charger in engineering, proper distro for atmos, 
del: Removed partial atmos can in SM room since that's not how cans are made anymore
qol: added layer manifolds for gas supply to pure
fix: removed engineering access from engi sec outpost.
/:cl:

2024-03-22 21:53 UTC, Pepsilawn commented
![Screenshot_20240322-225239_Chrome](https://github.com/fulpstation/fulpstation/assets/25415050/929b0766-2792-42c5-ae21-da94f0c7ce8f)

Why is this back is it even connected to anything

2024-03-22 22:00 UTC, Pepsilawn commented
The streamlined atmos set up is counter productive, there are plenty of missing components such as Mix to Distro being non-existent

2024-03-22 22:10 UTC, Pepsilawn requested changes
See previous two comments

2024-03-22 22:20 UTC, Pepsilawn commented on _maps/map_files/SeleneStation/SeleneStation.dmm
> +	name = "Distro Stagsing to Filter"
what does that mean

2024-03-22 22:20 UTC, Pepsilawn commented
There's a rogue edit in ordnance and I'm not sure what you mean by an access issue regarding the sec office

2024-03-23 12:20 UTC, Sadboysuss commented on _maps/map_files/SeleneStation/SeleneStation.dmm
> +	name = "Distro Stagsing to Filter"
fixed

2024-03-23 12:21 UTC, Sadboysuss commented
> The streamlined atmos set up is counter productive, there are plenty of missing components such as Mix to Distro being non-existent

expanded distro staging:
![image](https://github.com/fulpstation/fulpstation/assets/96586172/95f5203d-4c40-428d-ba3f-551414b1f2af)

2024-03-23 12:24 UTC, Sadboysuss commented
updated screenshots to reflect latest commit

2024-03-23 21:51 UTC, Pepsilawn commented
A bit excessive with the black pipe going around the whole thing this pipeline already serves this purpose just fine

![image](https://github.com/fulpstation/fulpstation/assets/25415050/66bdc4f0-e8a2-4974-923c-25dfb571935a)

2024-03-24 10:03 UTC, Pepsilawn commented
I'm quite cool with the atmos and SM room change, id like the portables being moved to the hallway change being reverted though, scrunching aux storage makes it look worse and isnt worth the change. One way to keep the portables outside would be to move all of tile storage two tiles to the left to take over the empty maintenance space and being able to throw them in the new 4 tiles that got freed up

![image](https://github.com/fulpstation/fulpstation/assets/25415050/60cf05c9-0bc6-435f-a755-e338437dfd02)
like this not sure if the illustration is explanatory enough

the decaling above CE office needs to be fixed too as they were done with the portables in mind

2024-03-24 12:38 UTC, Pepsilawn approved these changes

2024-03-24 12:38 UTC, merged

2024-03-24 13:05 UTC, Sadboysuss commented
hell yeah