[NOT READY] Adds Antagonist tips
fulpstation/fulpstation pull request #118
Opened 2021-04-13 03:45 UTC by SgtHunk

## About The Pull Request

???????

![image](https://user-images.githubusercontent.com/68669754/114491859-5e7d0600-9be5-11eb-9d37-058ebf07c35a.png)

TO DO:

- [ ] Finish
- [ ] Get a handful of antag tips done
- [ ] Make sure nothing is broken
- [ ] Make it a preference option (sadly can't be modular)
- [ ] Get all the .pngs IMAGES GOD THIS PART IS THE MOST TEDIOUS ONE

## Why It's Good For The Game

Literally new player friendly???????????????????

## Changelog
:cl:
add: Added tips for when you get certain antagonists, to know the basics.
/:cl:

2021-04-13 04:09 UTC, EgorDinamit commented on fulp_modules/antag_tips/code/antag_tip_integration.dm
> +/datum/antagonist/traitor/finalize_traitor()
You probably want to put just "/datum/antagonist/proc_name" there, otherwise it will only show up for traitors and subtypes.

2021-04-13 04:11 UTC, EgorDinamit commented
No idea how good is the idea of utilizing html pages for antag tips, especially for traitors, since you'd be better off making it show a tip for an uplink player is currently using, instead of everything.

2021-04-13 07:50 UTC, JohnFulpWillard commented on fulp_modules/bloodsuckers/code/antagonists/bloodsucker_datum.dm
> +	// tips = BLOODSUCKER_TIPS
There's some coding changes I want to do before bloodsuckers / monster hunters get added, please leave them uncommented and I'll do them once this PR is merged

2021-04-13 21:39 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/abductor.html
> +	<p><img src="alienorgan.png"/>After that, he must do the <b>experimentation surgery</b>.</p>
extraterrestrial experimental surgery. we dont want them doing default since it requires taking clothes off.

2021-04-13 21:43 UTC, JohnFulpWillard requested changes

2021-04-13 21:43 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/changeling.html
> +	<p>The goal of many changelings is to acquire 5-7 DNA strains. To do this, it must take ANY human, living or dead, and acquire their DNA.</p>
I don't see why we should bring up that its a possible objective, just say its a way to steal DNA

2021-04-13 21:43 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/changeling.html
> +	<p>Absorbing a human will allow you to <b>readapt</b> and purchase different abilities.</p>
you should say body instead, to prevent them from murdering random crewmates because "the tip said so"

2021-04-13 21:43 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/cultist.html
> +	<h1>You are a Cultist!</h1>
should call them Blood Cultist instead, because heretics/tech cult

2021-04-13 21:43 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/nukie.html
> +	<p>As a Nuclear Operative, you have different options for purchase such as the Mauler<img src="mauler.png"/>or the Energy Shield<img src="eshield.png"/>.</p>
Is this part necessary?

2021-04-13 21:43 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/nukie.html
> +	<p>Declaring war stops you from going to the station for 20 minutes, alerts the crew and gives the entire team telecrystals.</p>
They can leave at 18

2021-04-13 21:43 UTC, JohnFulpWillard commented on fulp_modules/antag_tips/html/wizard.html
> +	<p>The details of your objective are stored within your notes, to see them use the Notes verb.</p>
Since wizards dont care for objectives, should we even bring this up?

2021-04-20 22:10 UTC, ATH1909 commented on fulp_modules/antag_tips/html/nukie.html
> +	<p>Declaring war stops you from going to the station for 20 minutes, alerts the crew and gives the entire team telecrystals.</p>
no, they can't.

```
#define SYNDICATE_CHALLENGE_TIMER 20 MINUTES
```
```
	if(board?.challenge && world.time < SYNDICATE_CHALLENGE_TIMER)
		to_chat(user, "<span class='warning'>You've issued a combat challenge to the station! You've got to give them at least [DisplayTimeText(SYNDICATE_CHALLENGE_TIMER - world.time)] more to allow them to prepare.</span>")
		return FALSE
```

2021-05-08 00:52 UTC, closed without merging