Adds Fulpstation spell granters and associated space ruins
fulpstation/fulpstation pull request #1270
Opened 2024-11-11 00:01 UTC by QuiteLiterallyAnything

## About The Pull Request
This PR adds in two new spell granters for both Fulpstation spells currently available. 
<details><summary>Expand to see the sprites for the new spell granters</summary>

![image](https://github.com/user-attachments/assets/1e5a52e9-e70f-41f2-8a91-66483893e685)
_Both icons are slightly animated._

</details>

This PR also adds in two new space ruins containing both spell granters as loot. (The ruin for the cateor spell granter has a mild hazard to account for the spell's value in combat.)
<details><summary>Expand to see direct StrongDMM screenshots of both new ruins</summary>

![image](https://github.com/user-attachments/assets/7396f56f-2766-43b7-bff9-9de62cd92481)
_"Direct Cat Meteor" spell book ruin._

![image](https://github.com/user-attachments/assets/815b1cb8-3c02-4137-b837-289a37136564)
_"Summon Dancefloor" spell book ruin._
</details>

## Why It's Good For The Game
There's practically no way for players to get either of these spells at the moment (aside from hoping for extreme luck with the Greed ruin on Lavaland,) and this PR addresses that by adding in a way to get them.

## Changelog

:cl:
add: Added spell book granters for both "Summon Dancefloor" and "Direct Cat Meteor"
add: Added two new space ruins containing the previously mentioned spell book granters
/:cl:

2024-11-13 09:29 UTC, JohnFulpWillard approved these changes
now if only we had pop for wiz rounds

2024-11-13 09:30 UTC, JohnFulpWillard requested changes

2024-11-13 09:30 UTC, JohnFulpWillard commented on fulp_modules/features/spells/spell_granters/summon_dancefloor.dm
> +	sleep(4 SECONDS)
Actually please get rid of sleeps, use timers instead

2024-11-14 01:05 UTC, QuiteLiterallyAnything commented on fulp_modules/features/spells/spell_granters/summon_dancefloor.dm
> +	sleep(4 SECONDS)
Done, thanks for the review! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

2024-11-14 16:23 UTC, JohnFulpWillard commented on fulp_modules/features/spells/spell_granters/summon_dancefloor.dm
> +	playsound(get_turf(user), 'sound/effects/wounds/crack1.ogg', 37, frequency = -1)
```suggestion

/obj/item/book/granter/action/spell/fulp/summon_dancefloor/proc/comedic_premonition(mob/living/user)
	to_chat(user, span_bolddanger("You might've just broken something..."))
	playsound(get_turf(user), 'sound/effects/wounds/crack1.ogg', 37, frequency = -1)
	addtimer(CALLBACK(src, PROC_REF(dance_injury), user), 2 SECONDS)
```

2024-11-15 22:23 UTC, merged