Heliostation sm waste and scrubber pipe layer fixes
fulpstation/fulpstation pull request #141
Opened 2021-04-26 03:12 UTC by EIB0N

## About The Pull Request

This changed the smart pipes for the scrubbers and exhaust from layer 3 to layer 2 like the rest of the scrubbers around the station

## Why It's Good For The Game

Help out the Engineering boys be more organized

## Changelog
:cl:
fix: SM Scrubber and exhaust are now layer 2!
/:cl:

2021-04-26 23:04 UTC, Helianthus00 commented
![image](https://user-images.githubusercontent.com/64755361/116161627-51661980-a6b1-11eb-8e26-0eb7ea54f722.png)
As far as I know, this does not work. A far better solution is to just change the color to something else that is not used in this area. Then I'd keep the rest of the pipes on layer 3 as normal so that the rest of the layers are reserved for extra pipes.

2021-04-26 23:05 UTC, Helianthus00 requested changes
![image](https://user-images.githubusercontent.com/64755361/116161739-8ffbd400-a6b1-11eb-9190-6550f100d850.png)
As far as I know, this doesn't work. You need to change the color of the pipes in the wastenet instead and leave everything else on layer 3.

2021-04-28 00:04 UTC, EIB0N commented
Fixed it

2021-04-28 01:20 UTC, Helianthus00 requested changes
![image](https://user-images.githubusercontent.com/64755361/116331693-89428f00-a78d-11eb-9551-efda26a3c3a8.png)
This gas meter is on the wrong layer. Please make sure you test this as well to make sure there aren't unintended issues. I still don't like the use of layer 2 scrubber pipes in the chamber.

2021-04-29 23:24 UTC, EIB0N reviewed
gas flow meter changed to layer 2

2021-04-30 01:17 UTC, Helianthus00 requested changes
![image](https://user-images.githubusercontent.com/64755361/116636800-6f38b600-a91f-11eb-9072-bea0da514061.png)
Making this pipe brown means it will no longer connect with the red pipes. You need to change it back to red or it won't work.

2021-05-02 21:57 UTC, Helianthus00 commented on tgstation.dme
> -#include "fulp_modules\ZFulpcode\modules\jobs\inventories.dm"
This shouldn't be removed.

2021-05-02 22:05 UTC, Helianthus00 requested changes
![1](https://user-images.githubusercontent.com/64755361/116829089-2de31900-ab60-11eb-83b5-e0461ce4465b.PNG)
![2](https://user-images.githubusercontent.com/64755361/116829092-2facdc80-ab60-11eb-97e1-86dc6982dd4f.PNG)
You don't need pipe bridges here. They are only needed if the pipes are the same layer.

2021-05-02 22:14 UTC, EIB0N reviewed
Fixed the pipe colors and removed the bridges

2021-05-02 22:14 UTC, EIB0N commented on tgstation.dme
> -#include "fulp_modules\ZFulpcode\modules\jobs\inventories.dm"
readded it

2021-05-02 22:20 UTC, Helianthus00 commented on tgstation.dme
> -#include "fulp_modules\ZFulpcode\modules\jobs\inventories.dm"
it needs to be in alphabetical order

2021-05-02 22:30 UTC, Helianthus00 approved these changes

2021-05-02 22:39 UTC, merged