New Necropolis
fulpstation/fulpstation pull request #21
Opened 2021-01-12 04:55 UTC by John-Dang

## About The Pull Request
This is a complete rework of the Ash Walker Nest, this is the Ash Walker Town, a whole new Necropolis! The temple has been moved to the center of the village, and has been made larger and given two adjoining rooms and an altar, trying to make it feel like a real central temple the tribe is focused around. The clinic has been moved and reworked to be a shaman's hut, with makeshift surgery tools, mourning poultice and aloe. Residential room has been added with small dining table, dirty mattresses and chests with 4 guard/hunter loadouts, 1 architect loadout, and 1 farmer loadout. Village Chief's office has been added, with a throne and a couple minor trophies for the chief to hold meetings or hearings with villagers/outsiders. Attached to the clinic is a commissary, which could be used internally or with those passing by. The farm has also been reworked, with more plots, seeds for bufo, cotton, bamboo, aloe, towercap and glowcap. The bodies are replaced with charred skeletons.

![image](https://user-images.githubusercontent.com/38540951/104271188-41ab2800-5468-11eb-8b16-7715af918b0e.png)
![image](https://user-images.githubusercontent.com/38540951/104271207-4cfe5380-5468-11eb-8ac6-af2b0a1ef412.png)

## Why It's Good For The Game
Reworks the Necropolis to be more of a village, gives more RP opportunity and visual distinction between villagers, gives them more to interact with and more to do. Also, removes the Malf AI disk and syndicate toolbox from the village area.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-01-12 05:16 UTC, remove32 commented
just make sure to update the CL section when you open it.
youll probably get some other feedback later as well

2021-01-13 02:16 UTC, Helianthus00 commented
Overall, I like it. However, I think that giving a crown/throneroom is not exactly fitting in lorewise. This space could be used better. The door on the bottom right room is also blocked by rocks, so that should be changed. Removing the syndicate stuff removes the extra hint over how they got the modern equipment, and I feel like removing that with no analog is a bad idea.

2021-01-13 15:14 UTC, SgtHunk requested changes

2021-01-13 15:14 UTC, SgtHunk commented on tgstation.dme
> +#include "code\Fulp_Code\datums\lavaland.dm"
This file no longer exists

2021-01-14 12:38 UTC, Gurkenglas commented
The malf AI disk gave the station a reason to interact with Ashwalkers through trade or raiding. It lets AI players learn the malf controls before playing as antag. Why remove it?

2021-01-19 19:07 UTC, ATH1909 commented
"Also, removes the Malf AI disk and syndicate toolbox from the village area."
cringe

as mentioned by gurk, the malf AI disk is fun and lets AIs learn how being a malf AI works without risking an antag round over it, and the syndicate toolbox expands the number of construction projects and surgeries available to the ash walkers immensely.

2021-01-19 23:50 UTC, ATH1909 commented
also also, will ash walkers still have enough cloth to make some backpacks after this change?

2021-01-20 13:28 UTC, John-Dang commented
You raise a good point about the Malf AI disk! I'll re-add it and do another push in a hot minute. Although is replacing the syndicate toolbox with a regular toolbox alright?

2021-01-20 14:26 UTC, John-Dang commented
I am going to try and make a new branch since people on the coderbus server told me to because mine is hilariously out of date they say, so I'm going to close this one and try to open on a new, more up to date branch.

2021-01-20 14:26 UTC, closed without merging