Selene permabrig attempt 2
fulpstation/fulpstation pull request #313
Opened 2021-07-31 17:19 UTC by JohnFulpWillard

## About The Pull Request

Last one was denied so rip wacky escapists reference

![seleneperma](https://user-images.githubusercontent.com/53777086/127747658-44a380b1-8cfe-4fa5-b899-09889cbaeb62.png)

## Why It's Good For The Game

oh boy I cant wait to play my favor...

2021-08-01 00:29 UTC, JohnFulpWillard commented
who the hell is conflciting with hos prefix

2021-08-02 00:29 UTC, Helianthus00 requested changes
![image](https://user-images.githubusercontent.com/64755361/127790192-832c2749-cf1c-478c-bcd9-59545a0b148e.png)
This area is quite... awkward. I'd move that botany stuff to the middle of the botany room and just have a neater entrance to the restroom. 

Also the floor colors kinda make me feel sick. Stick grey and one other color for checkered please.

2021-08-03 20:17 UTC, JohnFulpWillard commented
![image](https://user-images.githubusercontent.com/53777086/128080314-a92c7b29-d216-405d-8f9f-9a553ae35688.png)
lol

2021-08-04 02:16 UTC, Helianthus00 approved these changes

2021-08-04 02:16 UTC, merged