Create emergency_xeno shuttle
fulpstation/fulpstation pull request #434
Opened 2021-12-12 15:47 UTC by TheOnlySolitaire

## About The Pull Request

New shuttle based on an pre-existing shuttle that has been overrun by Xenos. 
The end-goal is to have the shuttle be unlocked by scanning a xenos organ and/or by purchasing the corresponding xeno research. 

## Why It's Good For The Game

New shuttle adds to options and fun in the game.

## Changelog

:cl:
add: Adds new shuttle
/:cl:

2021-12-12 15:52 UTC, SgtHunk commented
How does this interact with shuttle-stalling antags, now that because of the shuttle we have 10+ facehuggers that will make player-controlled xenos

2021-12-12 22:52 UTC, TheOnlySolitaire commented
> How does this interact with shuttle-stalling antags, now that because of the shuttle we have 10+ facehuggers that will make player-controlled xenos

Very good point. I think Shuttle Hijack could be considerably harder, though a clever antag might use this shuttle to assist in preventing other crew getting onboard so they just need to focus on the hijacking and surviving part. But for sure preventing crew from escaping would become easier. 

Something to consider though is that there are the cult and doom arena shuttles, thats off the top of my head and there may be a couple more, which also have this issue. Is this that far different? 
Would balancing the number of possible player controlled mobs/facehuggers make it more agreeable?

2021-12-13 13:35 UTC, StoneMason commented
If there's a blob, revolution or even a smart cult, the shuttle will arrive and self-antaggers/dumbasses will sprint onto the shuttle and get facehugged. Whilst it probably wouldn't be a huge issue as captain's rarely go for cool shuttles, this shit will definitely cause a xeno outbreak a few times. Just make it like the lavaland ruin so it's xenomobs and popped eggs.

2021-12-13 15:24 UTC, SgtHunk requested changes
Remove the xeno eggs entirely. A shuttle shouldn't be bringing an antag onto the station. It can include enemies a la cult shuttle, but having people get facehugged and bring xenos is just too much.

2021-12-14 03:52 UTC, wraith-54321 commented
1 egg in a command only area could work, I dont know, or you could just give the xeno mobs a fun balloon like in the cult shuttle

2021-12-22 13:21 UTC, TheOnlySolitaire commented
I will remove the eggs and just leave mobs, is it ok for those mobs and at least for now, remove the sentience balloon to let them be player controlled. If thats ok and requested I'll re-add it but eggs will be gone on next commit.

2021-12-27 18:39 UTC, Helianthus00 commented
This seems a little odd to just have available to order at any time. If you lock it behind something like emag or xeno research, I'd be more willing to consider this.

2022-01-08 20:22 UTC, JohnFulpWillard commented on fulp_modules/mapping/shuttles/map_templates.dm
> +	prefix = "fulp_modules/mapping/shuttles/evac/"
delete this line

2022-01-08 23:48 UTC, TheOnlySolitaire commented
> This seems a little odd to just have available to order at any time. If you lock it behind something like emag or xeno research, I'd be more willing to consider this.

It was always planned to be, I just needed to figure it out. I've updated the file so that it now has:

- locked the shuttle behind alien tech
- removed Queen and Praetorian
- removed all xeno eggs
- removed sentience balloon
- tweaked xeno mobs so there are 7 total, 3 drones, 3 sentinels and 1 non-hostile larva

2022-01-08 23:48 UTC, closed without merging