removes nearly all borg positions
fulpstation/fulpstation pull request #597
Opened 2022-04-12 10:16 UTC by JohnFulpWillard

## About The Pull Request

Brings Cyborg positions down to 1 (latejoin is still disabled).

## Why It's Good For The Game

Cyborgs spawning roundstart is something I've never been a fan of. Cyborg isn't a job, it's a role. You transition into one through borging.
I'd rather people who want to play Cyborg would go Assistant instead, and turn into one through Robotics. This gives Robotics a thing to do early in the shift, gives Miners a reason to get materials early on in the shift, and makes Cyborgs feel closer to the Robotics department as a whole, as they created your shell and did the surgery needed to get you in there.
I find Cyborgs with this, would be more likely to actually respect the Robotics department, and even return later for upgrades or model resets, something basically never see nowadays.

I also kept a single cyborg slot, because sometimes no one wants to be borged, and in a case of a malf AI or such, you need at least one borg to use something like the force borger.

2022-04-12 10:19 UTC, OneAsianTortoise commented
One thing I want to mention is that I am fairly certain that silicon hour only counts if you are round start borg, therefore, players who want to unlock AI must take round start borg.

But Idrc because I hate em.

2022-04-12 10:21 UTC, JohnFulpWillard commented
> One thing I want to mention is that I am fairly certain that silicon hour only counts if you are round start borg, therefore, players who want to unlock AI must take round start borg.
> 
> But Idrc because I hate em.

![image](https://user-images.githubusercontent.com/53777086/162939381-9f884c4d-9bbe-425c-a52d-03d3daf65aba.png)

2022-04-12 19:15 UTC, Pepsilawn commented
Ninja nerf

2022-04-14 00:29 UTC, Helianthus00 requested changes

2022-04-14 00:29 UTC, Helianthus00 commented on fulp_modules/Z_edits/job_edits.dm
> +	spawn_positions = 1
```suggestion
	spawn_positions = 2
```
Make it two and we've got a deal

2022-04-14 03:35 UTC, Helianthus00 approved these changes

2022-04-14 03:35 UTC, merged