Heliostation Patch 2 - Engineering Complete Revamp; Minor Service Revamp; Crate Economy Balance
fulpstation/fulpstation pull request #851
Opened 2022-11-19 16:19 UTC by OneAsianTortoise

## About The Pull Request
What I see as issue in current helio engineering:

- Compelte Revamp Enginnering department
- Adds service hallway
- Tweaks service/engi maint
- Balance Crate economy
`crate_abandonded - from 12 to 2 (Fuck you @Ebb-Real)[Icebox - 2; Meta - 0; Delta - 1]`
`crate_loot - from 11 to 1[Icebox - 0; Meta -1; Delta - 3]`
`crate - amount of crate cut in half`
Heliostation crate economy is doomed.

<details>
<summary>Before</summary>
<img src="https://user-images.githubusercontent.com/64306407/202860796-a44c4057-f60e-467b-981e-cfdd14b167a2.png">
</details>

<details>
<summary>After</summary>
<img src="https://user-images.githubusercontent.com/64306407/202860648-1719e52b-e76a-4371-9fe6-827ab7f4209e.png">
</details>

## Changelog

:cl:
Engineering Complete Rework; Minor Service Revamp; Crate Economy Balance
/:cl:

2022-11-19 21:49 UTC, SgtHunk requested changes
# **Review**
<details>
<summary>Engineering Lobby:</summary>
<br>
8.5/10. The design looks good, and not overwhelming. I'm gonna nitpick a bit because of the decal'ing used throughout a lot, so just be prepared lol. The decals used to position the portable atmos machinery was well done, and I like the stairs. Now my decal nitpick is that I *personally* don't think trimline goes well with side tiles, it is your design though so up to you if you want to change it. Also the disposal bin and APC aren't connected.
</details>

<details>
<summary>Engi/Cargo Hallway:</summary>
<br>
9/10. It looks pretty dynamic, and it's not unpleasant to look at, the benches and vendors give it more life. What I'm noticing is a distinct lack of cameras and lights, so I'd become an AI to test the view range. The two firelock alarms to the right of tech storage look kinda wacky together seeing how players will be able to see both of them at once, I'd advise putting it to the side so you only need one while still being clickable.
</details>

<details>
<summary>Gravity Generator:</summary>
<br>
7/10. It remained about the same as it didn't need much modification, but the decal'ing was only done in one room and looks inconsistent, seeing how the other two rooms (the gravity gen itself and the access) are just sidings. The note is a nice detail though.
</details>
<details>
<summary>Owl Room:</summary>
<br>
9/10. Awesome tbh, nothing about it is bad, only the fact there's no airlock in lol. You can use an abandoned airlock helper if you don't want it to be easily accessible. It's fine walled in, but if you do change it to an airlock it'd also be nice having a tinted window.
</details>
<details>
<summary>AI Minisat Access:</summary>
<br>
7/10. It's okay, it works. The design's simple even if not to my taste. I kinda hate the positioning being shoved in because there was no space, Might be better off moved to science (coming in the sci rework 2022).
</details>
<details>
<summary>Tech Storage:</summary>
<br>
7/10, room design isn't bad but decals could be better, there's too much yellow in the room. I think you could get away with using iron + smooth tiles, with a bit of trimline. Neutral tiles wouldn't go bad either, if looking for references I'd say Delta's public tool storage and Pubby's (?) Tech Storage. Also missing airlock lol and could use a bit more light.
</details>
<details>
<summary>Engi/Atmos Access:</summary>
<br>
 8/10. Pretty simple, Vent isn't connected tho, and you could add cyclelinks.
</details>
<details>
<summary>Sec Post:</summary>
<br>
8/10. Simple design but it does the job, no way you can go wrong with it but maybe you could do something with the decals idk up to you.
</details>
<details>
<summary>Atmos Desk:</summary>
<br>
9.5/10. Amazing, not too convoluted. Vents and scrubbers need to be connected, same with disposal bin. Idk too much about siding but it isn't too excessive so it should be fine, I think it'd look good if you also added neutral tile decals to the dark tiles.
</details>
<details>
<summary>Engi Desk:</summary>
<br>
Same as atmos desk, it's pleasant to look at, same advice. APC needs to be connected.
</details>
<details>
<summary>TComms Desk:</summary>
<br>
8/10. The room is fine but the command blue decals are kinda ruining the vibe ngl, they just don't fit too well and maybe just using regular iron tiles + bot decals and a bit of trimline might be enough. APC not connected.
</details>
<details>
<summary>TComms:</summary>
<br>
 9/10. Looks good, not much else to point out. APC is not connected. There not being any pointers to which department is which is fine tbh, people can read and if there needed to be any I think it'd have to be done on the machine sprite  like techfabs instead of changing the decals.
</details>
<details>
<summary>Engi Hallway:</summary>
<br>
7/10. Same nitpick as lobby with the decal/tile matching. Vent/Scrubber/APC needs connecting.
</details>
<details>
<summary>Engi/Atmos Break Room/Techfab:</summary>
<br>
7/10. Too much siding and the side tiles just make the room feel weird, the positioning of everything is fine but it just looks a bit odd. I think it'll look good if you split the room with tiles, making everything past the thin windows wood to signify the break room and the other half just being themed more around engineering.
</details>
<details>
<summary>Atmos Storage:</summary>
<br>
8/10. Not bad in terms of positioning and what's in it, just decals and stuff. Also the maint around it looks like it wants to reach to an airlock but it doesn't, might wanna change the room a small bit and add a maint airlock.
</details>
<details>
<summary>Engi Storage:</summary>
<br>
8/10, same details as atmos storage. I think the vent/scrubbers would look better if they were centered so they're in the same Y axis.
</details>
<details>
<summary>CE Office + Bedroom:</summary>
<br>
9/10. I really like the bedroom. The main office though could use some work, the stripe can work but I think you should be consistent with sectioning off computers in the office if that's the case, so I think it'll look better if you section off the two tables + printer with dark tiles.
</details>
<details>
<summary>Engine Room:</summary>
<br>
9/10. I don't know how to feel about the access being red, but it works. The engine room itself is good, though. There's a lot going on and it captures the feel of Engineering.
</details>
<details>
<summary>Supermatter Room:</summary>
<br>
7.5/10. The room itself is fine, it looks about the same as Old Helio though. Spamming reinforced floor is a bit weird seeing how an explosion wrecks them anyways lol, maybe normal iron tiles will do. And same as earlier, idk if red fits engineering well. Maybe cut down on the warning lines, and add warning lines there with textured dark tiles.
</details>
<details>
<summary>Distro Loop:</summary>
<br>
9/10. Nice room, decent size and communicates itself well. Kilo vibes.
</details>
<details>
<summary>Atmospherics:</summary>
<br>
8.5/10. This is a big empty room so idk how it could be improved, I think it's fine as it is. Maybe a bit of a decal fix, like adding a small separator in the 3x1 areas where the computers are so the colors don't clash as bad.
</details>
<details>
<summary>HFR Room:</summary>
<br>
9.5/10. Cool room, try using trimline mid-joiners seeing as how you're using full tiles. Also I can't find the radiation shutters button idk.
</details>
<details>
<summary>Turbine Room:</summary>
<br>
9.5/10. I like the design of it, it could use a bit more color but it looks good.
</details>
<details>
<summary>Maintenance:</summary>
<br>
10/10. You captured it perfectly, It looks a lot less flat and just generally feels more dynamic.
</details>
<details>
<summary>Service Hall:</summary>
<br>
9/10. Yeah. Not bad, a bit too tight but it is just maintenance turned into a hallway, so pretty good considering what you had to work with.
</details>

2022-11-21 19:10 UTC, Ebb-Real commented
> * Balance Crate economy
>   `crate_abandonded - from 12 to 2 (Fuck you @Ebb-Real)[Icebox - 2; Meta - 0; Delta - 1]`
>   `crate_loot - from 11 to 1[Icebox - 0; Meta -1; Delta - 3]`
>   `crate - amount of crate cut in half`
>   Heliostation crate economy is doomed.

hii

2022-12-04 05:10 UTC, OneAsianTortoise commented
I will open new one in another time.

2022-12-20 02:16 UTC, SgtHunk approved these changes

2022-12-20 02:16 UTC, merged